### ISSUE TITLE
Список всех адресов РФ

### ISSUE THREAD

**Issue by konalegi** [runetfreedom/russia-v2ray-rules-dat#3]
А нельзя ли получить какой то список, чтоб на роутере настроить что в РФ ходил по напрямую, а все заграничное по proxy?

**Comment by runetfreedom** [comment]
В правиле "Всё, кроме РФ" так и сделано.

Это просто `geoip:ru`

**Comment by konalegi** [comment]
А, блин. А нет смысла это добавить в документацию? Или я ее просто плохо читал? Я основывался на geoip.dat/geosite.dat секциях readme. 
В любом случае, issue можно закрыть, действительно работает, спасибо большое!
