### ISSUE TITLE
Настройка для FoXray

### ISSUE THREAD

**Issue by noideastowork** [runetfreedom/russia-v2ray-rules-dat#6]
Подскажите, пожалуйста, а можно ли как-то настроить это для FoXray? 

Если нет, то в каком клиенте на macOS это можно реализовать?

**Comment by LimonJohn** [comment]
Хз, но своё исследование данного вопроса вы можете начать с документации на [сайте](https://yiguo.dev/docs/apple/routingdns/) разработчика.

**Comment by noideastowork** [comment]
@LimonJohn спасибо! сам тыкался до этого - не получилось, посмотрел документацию, к сожалению, не обнаружил там нужной информации (возможно, слепой)

просто мне почему-то казалось, что автор этого репозитория где-то как будто упоминал что-то про foxray

upd: нашел, что именно сказал автор: "У меня в планах было сделать еще и правила маршрутизации для FoxRay (клиент для iOS/macOS), но разработчики клиента недавно удалили поддержку импорта правил." и я вот немного не понимаю, как это интерпретировать, либо никак нельзя импортировать вообще туда файлики (вроде можно, там есть импорт как таковой), либо никак нельзя это автоматизировать через пару кликов 

<img width="884" alt="image" src="https://github.com/user-attachments/assets/51bcabca-c927-49a2-aee2-861df2c937cb" />

**Comment by runetfreedom** [comment]
@noideastowork я вижу, что вы уже загрузили кастомные файлы. Вы можете использовать их в правилах маршрутизации вот так:
```ext:geosite-ru-only.dat:category-ads-all```

Имейте в виду, что это не заработает на айфоне, так как его network extension ограничен, на сколько я помню, 50мб памяти. Из-за этого попытка загрузить какое-то заметное кол-во правил приведет к остановке туннеля операционной системой.

**Comment by noideastowork** [comment]
@runetfreedom спасибо большое за ответ!

я как раз по этому формату и пытался вносить правила, но это почему-то не работает:

1) ext:geosite-ru-only.dat:ru-blocked

<img width="890" alt="Снимок экрана 2024-12-17 в 14 33 07" src="https://github.com/user-attachments/assets/421d6c0b-2952-4bff-b7dd-a62a08b1c763" />

при такой настройке foxray подключается, но заблокированные сайты не грузятся. **видимо, на macOS тоже не вариант так настроить** (из-за network extension?)

2) ext:geosite-ru-only.dat:category-ads-all

аналогичная ситуация: при такой настройке (только вместо proxy - reject) foxray подключается, но рекламные домены, мне показалось, тоже грузились. но, справедливости ради, на андроиде я тоже потестировал category-ads-all и тоже разницы никакой не заметил

3) при использовании ANTIFILTER-DOWNLOAD-COMMUNITY или REFILTER сразу ошибка

предполагаю, что их нет в geosite-ru-only.dat

_infra/conf: invalid field rule
> infra/conf: failed to parse domain rule: ext:geosite-ru-only.dat:antifilter-download-community > infra/conf: failed to load external sites: antifilter-download-community from geosite-ru-only.dat > infra/ conf: list not found in geosite-ru-only.dat: ANTIFILTER-DOWNLOAD-COMMUNITY_

_infra/conf: invalid field rule
> infra/conf: failed to parse domain rule: ext:geosite-ru-only.dat:refilter > infra/conf: failed to load external sites: refilter from geosite-ru-only.dat
> infra/conf: list not found in geosite-ru-only.dat: REFILTER_

**Comment by runetfreedom** [comment]
Все верно, это уменьшенный список, там есть только `ru-blocked`, `private`, `category-ads-all`

Проверить можете, к примеру, на rutracker.

Но как по мне - самое удобное это пускать priavte и geoip:ru в direct, а остальное в прокси.

Так же не забывайте про очередность правил - сработает первое совпавшее правило.

**Comment by noideastowork** [comment]
@runetfreedom спасибо! в этот раз почему-то заработало ext:geosite-ru-only.dat:ru-blocked

чувствую себя немного сумасшедшим: я сделал все то же, что и в прошлые раз, но в этот раз все заработало. 

ну, максимум из того, что я сделал иначе - я начал с rutracker (а не того сайта, на котором я обычно испытываю блокировки). кроме этого, я, кажется, нажал включить/выключить/включить (несколько раз?) с разницей в секунд 30, потому что у меня rutracker в начале загрузился только частично (без css и картинок, они вроде на другом домене лежат - не на org, a на cc)

из гипотез только то, что из-за объема foxray нужно при первом запуске подумать до минуты, а потом все работает без приколов

еще раз спасибо! я еще потестирую, потыкаюсь, если пойму, что к чему, или найду причины, отпишусь. вдруг кто-то тоже попробует настроить
