### ISSUE TITLE
Все домены .ru

### ISSUE THREAD

**Issue by E-D-W-I-N** [runetfreedom/russia-v2ray-rules-dat#7]
Добрый вечер
Вопрос - а можно как-то у geosite получить все домены зоны ru?
По аналогии c `geoip:ru`

Просто есть проблема с рядом сайтов - у них иностранный IP, но российская доменная зона. Пример - https://2ip.ru/
Хочется настроить себе подключение, в котором в любые ru домены я буду ходить без VPN, а во все остальные с ним

**Comment by runetfreedom** [comment]
Здравствуйте!

Это во многом бесполезно, так как в реестре ркн сотни тысяч заблокированных доменов .ru, но если вы хотите, то в xray (и всех его клиентах вроде v2rayN&G и прочих) вы можете указать в правиле доменов просто 2 буквы `ru`.

Это правило будет захватывать всё TLD ru
![Screenshot](https://github.com/user-attachments/assets/777b0bb3-83e8-4f70-98d2-53b63d3ba29a)

Не забудьте поднять это правило вверх

**Comment by E-D-W-I-N** [comment]
Большое спасибо!
